-- Run this in Supabase Dashboard > SQL Editor.
-- The Flask backend uses the service role key, so do not expose that key in frontend JavaScript.

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  image_path text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists clients_category_sort_idx
  on public.clients (category, sort_order, id);

insert into public.clients (category, name, sort_order)
select category, name, sort_order
from (
  values
    ('Manufacturing', 'Apu Packaging Pvt Ltd', 1),
    ('Manufacturing', 'Aakrishi Pvt Ltd', 2),
    ('Manufacturing', 'Vapi Industries Ltd', 3),
    ('Enterprises', 'Regent Enterprises', 4),
    ('Enterprises', 'Dipali Enterprises', 5),
    ('Enterprises', 'Supreme Enterprises', 6),
    ('Logistics & Trade', 'Global Logistics', 7),
    ('Logistics & Trade', 'Supreme Infra Ltd', 8),
    ('Logistics & Trade', 'Coastal Traders Co.', 9),
    ('Tech & Services', 'Tech Solutions Inc', 10),
    ('Tech & Services', 'Vapi Group Industries', 11),
    ('Tech & Services', 'Gujarat Services Ltd', 12)
) as seed(category, name, sort_order)
where not exists (select 1 from public.clients);
